# Generated by Django 5.1.6 on 2025-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Data Science', 'Data Science'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Marketing', 'Marketing')], default='Other', max_length=255),
        ),
    ]
