# Generated by Django 5.1.6 on 2025-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.IntegerField(default='null'),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
