# Generated by Django 5.1.6 on 2025-02-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_contact_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
