# Generated by Django 5.1.6 on 2025-02-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_contact_alter_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Data Science', 'Data Science'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
