# Generated by Django 5.1.6 on 2025-02-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_category_alter_job_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
