# Generated by Django 5.1.6 on 2025-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Data Science', 'Data Science'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Marketing', 'Marketing')], default='Other', max_length=255),
        ),
    ]
