# Generated by Django 5.1.6 on 2025-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_contact_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
