# Generated by Django 5.1.6 on 2025-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
    ]
